
package taxcalculator;

/**
 *
 * @author Darpan
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        userInputTextField = new javax.swing.JTextField();
        personalAllowanceTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        taxableIncomeTextField = new javax.swing.JTextField();
        totalTaxTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        mainLabel = new javax.swing.JLabel();
        personalAllowanceLabel = new javax.swing.JLabel();
        taxableIncomeLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        niContributionTextField = new javax.swing.JTextField();
        niContributionLabel = new javax.swing.JLabel();
        monthlyRadioButton = new javax.swing.JRadioButton();
        annuallyRadioButton = new javax.swing.JRadioButton();
        netSalaryTextField = new javax.swing.JTextField();
        copyrightLabel = new javax.swing.JLabel();
        netSalaryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tax Calculator [v1.0 Jan2017]");
        setResizable(false);

        userInputTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userInputTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInputTextField.setText("00.00");

        personalAllowanceTextField.setEditable(false);
        personalAllowanceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        personalAllowanceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        calculateButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        taxableIncomeTextField.setEditable(false);
        taxableIncomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taxableIncomeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalTaxTextField.setEditable(false);
        totalTaxTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalTaxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        mainLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainLabel.setText("Please enter your income before any tax deductions:");

        personalAllowanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        personalAllowanceLabel.setText("Your tax free Personal Allowance:");

        taxableIncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taxableIncomeLabel.setText("Your taxable income: ");

        taxLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taxLabel.setText("Total income tax you pay:");

        niContributionTextField.setEditable(false);
        niContributionTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        niContributionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        niContributionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        niContributionLabel.setText("Your National Insurance contribution:");

        monthlyRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        monthlyRadioButton.setSelected(true);
        monthlyRadioButton.setText("Monthly");
        monthlyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyRadioButtonActionPerformed(evt);
            }
        });

        annuallyRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        annuallyRadioButton.setText("Annually");
        annuallyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuallyRadioButtonActionPerformed(evt);
            }
        });

        netSalaryTextField.setEditable(false);
        netSalaryTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        netSalaryTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        copyrightLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        copyrightLabel.setForeground(new java.awt.Color(51, 51, 51));
        copyrightLabel.setText("© 2017 DeltaRomeo");

        netSalaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        netSalaryLabel.setText("Salary after tax deductions:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyrightLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainLabel)
                                .addComponent(personalAllowanceLabel)
                                .addComponent(taxableIncomeLabel)
                                .addComponent(taxLabel)
                                .addComponent(niContributionLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(monthlyRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(annuallyRadioButton))
                                .addComponent(netSalaryLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(niContributionTextField)
                                .addComponent(userInputTextField)
                                .addComponent(personalAllowanceTextField)
                                .addComponent(calculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(taxableIncomeTextField)
                                .addComponent(totalTaxTextField)
                                .addComponent(netSalaryTextField)))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(monthlyRadioButton)
                    .addComponent(annuallyRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalAllowanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalAllowanceLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxableIncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxableIncomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(niContributionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niContributionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netSalaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLabel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        input = Float.parseFloat(userInputTextField.getText());
        
        TaxCalculator.main(null);
        
        personalAllowanceTextField.setText("");
        if(calculationType == "annually")
        {
            personalAllowanceTextField.setText(String.valueOf(PersonalAllowance.getAnnualPersonalAllowance()));
        }
        else if(calculationType == "monthly")
        {
            personalAllowanceTextField.setText(String.valueOf(PersonalAllowance.getMonthlyPersonalAllowance()));
        }
        
        taxableIncomeTextField.setText("");
        if(calculationType =="annually")
        {
            taxableIncomeTextField.setText(TaxCalculator.getAnnualTaxableIncome());
        }
        else if(calculationType == "monthly")
        {
            taxableIncomeTextField.setText(TaxCalculator.getMonthlyTaxableIncome());
        }
        
        totalTaxTextField.setText("");
        totalTaxTextField.setText(String.valueOf(IncomeTax.getIncomeTax()));
        
        niContributionTextField.setText("");
        niContributionTextField.setText(String.valueOf(NIContribution.getContribution()));
        
        netSalaryTextField.setText("");
        netSalaryTextField.setText(String.valueOf(input - (IncomeTax.getIncomeTax() + NIContribution.getContribution())));
        
        descriptionTextArea.setText(IncomeTax.getText());
    }                                               

    private void monthlyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        if(monthlyRadioButton.isSelected())
        {
            calculationType = "monthly";
            annuallyRadioButton.setSelected(false);
        }
        
    }                                                  

    private void annuallyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        if(annuallyRadioButton.isSelected())
        {
            calculationType = "annually";
            monthlyRadioButton.setSelected(false);
        }
    }                                                   

    
    /**
     * This method returns the input that the user had entered.
     * @return 
     */
    public static float getInput()
    {
        return input;
    }
    
    /**
     * This method returns the tax calculation type that the user had entered.
     * @return 
     */
    public static String getCalculationType()
    {
        return calculationType;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton annuallyRadioButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JRadioButton monthlyRadioButton;
    private javax.swing.JLabel netSalaryLabel;
    private javax.swing.JTextField netSalaryTextField;
    private javax.swing.JLabel niContributionLabel;
    private javax.swing.JTextField niContributionTextField;
    private javax.swing.JLabel personalAllowanceLabel;
    private javax.swing.JTextField personalAllowanceTextField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxableIncomeLabel;
    private javax.swing.JTextField taxableIncomeTextField;
    private javax.swing.JTextField totalTaxTextField;
    private javax.swing.JTextField userInputTextField;
    // End of variables declaration                   
    private static float input;
    private static String calculationType = "monthly";

}
